Expulsar cuentas que se unen a través del widget y tienen menos de 3 días de antigüedad
TheNozomi/ConfeBot pull request #17
Opened 2021-02-11 03:18 UTC by bitomic

Es un desastre, gracias. (?)

- `ReadyListener.ts` busca la invitación del widget actual y guarda su código y número de usos.
- `index.ts` define propiedades donde se guarda el código y número de usos de la invitación del widget actual.
- `MemberUpdateListener.ts` expulsa a un usuario si la cuenta fue creada hace menos de 3 días. Revisa si `client.widgetInvite.code` coincide con el código del widget actual:
- - **Coincide.** Si la diferencia de usos es de 1, expulsa al usuario.
- - **No coincide.** Actualiza la nueva invitación en `client.widgetInvite`. Si tiene 1 uso, expulsa al usuario.
- ARRUINADOS TODOS LOS ARCHIVOS PORQUE EL LINTER DECIDIÓ HACER BRRRRR, NO ME HAGO RESPONSABLE CHAO.

2021-02-11 13:43 UTC, TheNozomi requested changes

2021-02-11 13:43 UTC, TheNozomi commented on src/index.ts
> +    // set during t	// set during the 'ready' event
Preferiría que `widgetInvite` no sea una propiedad de `client`, si no que esté dentro de un objeto con nombre `store` (o similar), el cual sí sería un miembro de `client`. Un cambio bastante trivial, pero prefiero que quede claro que esos son datos que se crean y usan exclusivamente en runtime.

2021-02-11 23:29 UTC, TheNozomi commented
Felicidades, le ganaste a eslint!!

2021-02-12 02:30 UTC, TheNozomi requested changes

2021-02-12 02:30 UTC, TheNozomi commented on src/events/MemberUpdateListener.ts
> +            newMember.kick('Cuenta creada hace menos de 3 días.');
Se debería avisar al usuario el motivo de su expulsión, con una implementación similar a [https://github.com/TheNozomi/ConfeBot/blob/master/src/tasks/KickNonVerifiedMembers.ts#L23 KickNonVerifiedMembers] (es decir, expulsar aunque no se haya podido enviar un mensaje al usuario). Also, los métodos que retornan `Promise` (kick/send) deberían tener `client.logException` como handler de errores.

2021-02-12 18:24 UTC, bitomic commented
Algo me dice que no querías que pusiera el `.catch` en `logsChannel.send` (?)

2021-02-12 20:19 UTC, TheNozomi approved these changes

2021-02-14 03:42 UTC, merged